# This Ansible playbook adds packages to the
# Magma builder build minion image.
---
- import_playbook: ../common-packer/provision/local-builder.yaml
- hosts: all
  become_user: root
  become_method: sudo
  become: true

  tasks:
    - apt_key:
        url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
        state: present

    - apt_repository:
        repo: "deb https://download.virtualbox.org/virtualbox/debian focal contrib"
        state: present

    - apt: update_cache=yes name={{ item }} state=present
      loop: ['linux-headers-generic', 'linux-headers-4.15.0-50-generic', 'virtualbox-6.1', 'unzip']

    - apt: update_cache=yes name={{ item }} state=present
      loop: ['qemu', 'libvirt-daemon-system', 'libvirt-clients', 'ebtables', 'dnsmasq-base', 'libicu-dev', 'libxslt-dev', 'libxml2-dev', 'libvirt-dev', 'zlib1g-dev', 'ruby-dev', 'nfs-common', 'nfs-kernel-server']

    - get_url:
        url: https://releases.hashicorp.com/vagrant/2.2.14/vagrant_2.2.14_x86_64.deb
        dest: /tmp/vagrant_x86_64.deb

    - apt:
        deb: /tmp/vagrant_x86_64.deb

    - apt: update_cache=yes name={{ item }} state=present
      loop: ["qemu-kvm", "virt-top", "libguestfs-tools", "virtinst", "bridge-utils"]

    - community.general.modprobe:
        name: vhost_net
        state: present

    - shell: echo "vhost_net" | sudo tee -a /etc/modules
      args:
        executable: /bin/bash

    - community.general.modprobe:
        name: kvm_intel
        state: absent

    - shell: echo 'options kvm-intel nested=y' >> /etc/modprobe.d/dist.conf
      args:
        executable: /bin/bash

    - community.general.modprobe:
        name: kvm_intel
        state: present

    - service:
        name: libvirtd
        state: restarted
    - name: Create a directory if it does not exist
      file:
        path: /var/jenkins/
        state: directory
        owner: jenkins
        group: jenkins
        mode: '0755'
    - apt_repository:
        repo: ppa:ansible/ansible
        state: present
    - apt: update_cache=yes name={{ item }} state=latest
      loop: ['ansible']
    - name: Unarchive a file that needs to be downloaded (added in 2.0)
      unarchive:
        src: https://golang.org/dl/go1.15.2.linux-amd64.tar.gz
        dest: /usr/local/
        remote_src: yes
    - file:
        src: /usr/local/go/bin/go
        dest: /usr/local/bin/go
        state: link
    - file:
        src: /usr/local/go/bin/gofmt
        dest: /usr/local/bin/gofmt
        state: link
    - apt: update_cache=yes name={{ item }} state=latest
      loop: ["make", "build-essential", "libssl-dev", "zlib1g-dev", "libbz2-dev", "libreadline-dev", "libsqlite3-dev", "wget", "curl", "llvm", "libncurses5-dev", "libncursesw5-dev", "xz-utils", "tk-dev", "libffi-dev", "liblzma-dev", "python-openssl", "git", "unzip", "jq"]
    - git:
        repo: 'https://github.com/pyenv/pyenv.git'
        dest: ~/.pyenv
      become: jenkins
    - file:
        src: /home/jenkins/.pyenv/bin/pyenv
        dest: /usr/local/bin/pyenv
        state: link
    - shell: pyenv install 3.7.0 -f
      become: jenkins
    - get_url:
        url: https://github.com/docker/compose/releases/download/1.27.4/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0777'
    - name: set up jenkins user
      user:
        name: jenkins
        groups: sudo,docker,kvm,libvirt
    - shell: pip install junit2html

    - shell: vagrant plugin update
      become: jenkins
    - shell: vagrant plugin install vagrant-vbguest
      become: jenkins
    - shell: vagrant plugin install vagrant-disksize
      become: jenkins
    - shell: vagrant plugin install vagrant-libvirt
      become: jenkins
    - name: Sysctl fixes for LTE tests
      sysctl:
        sysctl_file: /etc/sysctl.d/99-magma.conf
        name: "{{ item }}"
        value: "0"
        state: present
        reload: yes
      with_items:
        - net.bridge.bridge-nf-call-arptables
        - net.bridge.bridge-nf-call-ip6tables
        - net.bridge.bridge-nf-call-iptables
        - net.ipv4.conf.all.rp_filter
        - net.ipv4.conf.default.rp_filter